# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 20:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bday_reminder', '0003_user_credential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_credential',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
