# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 20:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bday_reminder', '0004_auto_20160211_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_credential',
            old_name='User',
            new_name='user',
        ),
    ]
